name: Check format

permissions:
    contents: read

on:
    pull_request:
        branches:
            - main
            - dev

jobs:
    check-format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
              with:
                  node-version: "22"

            - name: Run prettier
              run: |
                  npx prettier --check . || {
                    echo -e "\033[0;31mCode formatting issues detected. Please run 'npm run format' to fix formatting issues.\033[0m"
                    exit 1
                  }
